name: polybot
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.9.*
  - fastapi
  - uvicorn
  - matplotlib>3
  - scikit-learn
  - pandas==1.*
  - pydantic
  - pytest
  - pytest-cov
  - flake8
  - pip
  - pip:
    - -r requirements.txt
    - -r test-requirements.txt
    - -e .
